apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-content
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Hello App</title>
      </head>
      <body>
        <h1>Hello from GitOps</h1>
        <p id="message">message=v1</p>
      </body>
    </html>
