apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - ../../base
  - namespace.yaml

images:
  - name: demo-client
    newName: localhost:5001/demo-client
    newTag: "20260223030331"
  - name: demo-api
    newName: localhost:5001/demo-api
    newTag: "20260223030331"

patches:
  - target:
      kind: Ingress
      name: demo
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: localhost
