apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - deployment-client.yaml
  - deployment-api.yaml
  - service-client.yaml
  - service-api.yaml
  - ingress.yaml
